# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "SaIL"
title:              "Soft Matter and Interfacial Phenomena Lab at the University of Buffalo"
description:        "SaIL is a soft matter and interfacial phenomena research group at the University of Buffalo."


# URL
url:                http://sail-yong.github.io
baseurl:            
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           kramdown

# Highlighter
highlighter:        rouge

# Navigation
nav:
  - name:           "home"
    href:           "/"
  - name:           "about"
    href:           "/about"
  - name:           "people"
    href:           "/people"
  - name:           "publications"
    href:           "/publications"
  - name:           "positions"
    href:           "/positions"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
  -
    scope:
      path:         ""
      type:         "people"
    values:
      layout:       "profile"


collections:
  people:
    output: true
    permalink: /people/:title/index.html
